export const openedJobs = [
    {
      jobTitle: "Full-Stack Developer",
      jobDepartment: "Engineering",
      jobLocation: "San Francisco, CA",
      jobType: "Full-Time",
      jobDescription: "Develop and maintain scalable web applications using modern frameworks.",
      jobResponsibilities: [
        "Design, develop, and deploy front-end and back-end services.",
        "Collaborate with designers and product teams.",
        "Write clean, efficient, and testable code.",
      ],
      jobQualifications: [
        "Bachelor’s degree in Computer Science or equivalent experience.",
        "Strong understanding of web development principles.",
        "Proficiency in both front-end and back-end technologies.",
      ],
      jobSkills: ["JavaScript", "React", "Node.js", "SQL", "REST APIs", "Git", "AWS"],
      jobExperience: "3+ years of experience in full-stack development.",
      jobEducation: "BSc in Computer Science, Software Engineering, or a related field.",
      jobCompensation: "Competitive salary with benefits, equity, and bonus.",
      jobStatus: "Open",
      numberOfApplicants: 12,
      jobLink: "https://company.jobs/fullstack-developer",
    },
    {
      jobTitle: "Data Scientist",
      jobDepartment: "Data Analytics",
      jobLocation: "New York, NY",
      jobType: "Remote",
      jobDescription: "Analyze and interpret complex data to drive informed decision-making.",
      jobResponsibilities: [
        "Develop predictive models and algorithms.",
        "Clean and organize datasets for analysis.",
        "Present insights and findings to stakeholders.",
      ],
      jobQualifications: [
        "Proficiency in machine learning frameworks and statistical methods.",
        "Strong problem-solving and analytical skills.",
        "Ability to communicate data insights effectively.",
      ],
      jobSkills: ["Python", "R", "SQL", "TensorFlow", "Power BI", "Data Visualization"],
      jobExperience: "2+ years of experience in data analysis or a related role.",
      jobEducation: "Master’s degree in Data Science, Statistics, or equivalent.",
      jobCompensation: "$90,000 - $120,000 annually with remote perks.",
      jobStatus: "Open",
      numberOfApplicants: 20,
      jobLink: "https://company.jobs/data-scientist",
    },
    {
      jobTitle: "DevOps Engineer",
      jobDepartment: "Operations",
      jobLocation: "Austin, TX",
      jobType: "Full-Time",
      jobDescription: "Automate and streamline development and deployment processes.",
      jobResponsibilities: [
        "Build and maintain CI/CD pipelines.",
        "Monitor and improve system performance.",
        "Collaborate with development and operations teams.",
      ],
      jobQualifications: [
        "Experience with cloud platforms and infrastructure as code tools.",
        "Strong knowledge of containerization and orchestration technologies.",
        "Excellent troubleshooting skills.",
      ],
      jobSkills: ["Docker", "Kubernetes", "Jenkins", "Terraform", "AWS", "Bash scripting"],
      jobExperience: "4+ years in DevOps or related roles.",
      jobEducation: "Bachelor’s degree in Computer Science or relevant certifications.",
      jobCompensation: "$100,000 - $130,000 annually with relocation assistance.",
      jobStatus: "Open",
      numberOfApplicants: 8,
      jobLink: "https://company.jobs/devops-engineer",
    },
    {
      jobTitle: "UI/UX Designer",
      jobDepartment: "Design",
      jobLocation: "Seattle, WA",
      jobType: "Part-Time",
      jobDescription: "Create user-centered designs for web and mobile applications.",
      jobResponsibilities: [
        "Collaborate with developers to implement designs.",
        "Conduct user research and usability testing.",
        "Design intuitive interfaces and user workflows.",
      ],
      jobQualifications: [
        "Strong portfolio showcasing design skills.",
        "Ability to create responsive and accessible designs.",
        "Experience in user research and prototyping.",
      ],
      jobSkills: ["Figma", "Sketch", "Adobe XD", "HTML/CSS", "User Research", "Prototyping"],
      jobExperience: "2+ years in UI/UX design.",
      jobEducation: "Degree in Design, Human-Computer Interaction, or similar.",
      jobCompensation: "$40 - $50/hour.",
      jobStatus: "Open",
      numberOfApplicants: 15,
      jobLink: "https://company.jobs/ui-ux-designer",
    },
    {
      jobTitle: "Cybersecurity Analyst",
      jobDepartment: "Security",
      jobLocation: "Remote",
      jobType: "Contract",
      jobDescription: "Monitor and safeguard company networks and systems against threats.",
      jobResponsibilities: [
        "Conduct risk assessments and vulnerability scans.",
        "Manage firewalls and intrusion detection systems.",
        "Respond to and investigate security incidents.",
      ],
      jobQualifications: [
        "Experience in network security and incident response.",
        "Strong understanding of cybersecurity frameworks.",
        "Ability to identify and mitigate security risks.",
      ],
      jobSkills: ["SIEM tools", "Firewalls", "VPN", "Cybersecurity frameworks (NIST, ISO 27001)"],
      jobExperience: "3+ years in cybersecurity or IT security.",
      jobEducation: "Bachelor’s in Information Security or related field.",
      jobCompensation: "$50/hour with a 6-month contract.",
      jobStatus: "Open",
      numberOfApplicants: 10,
      jobLink: "https://company.jobs/cybersecurity-analyst",
    },
  ];
  